package SavouryScore;
import java.util.Scanner;
/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {
    //Declarations


    public static String headingLine = "################################################################";
    public static String endLine = "----------------------------------------------------------------";
    public static String ratings ="[5] Sky High\n[4] High\n[3] Average\n[2] Low\n[1] Ultra Low";
    public static boolean enoughMeals = false;
    public static String name;
    // In retrospect, I should have made them all strings
    public static int cost;
    public static int  time;
    public static int taste;
    public static Scanner input = new Scanner(System.in);

    public static void logMeal(int getReports)
    {
        while(getReports == 0 || enoughMeals == false)
        {
            System.out.println(headingLine + "\nLOG A MEAL\n"+ headingLine);
            System.out.println(endLine + "\nPlease enter the meals name");
            name = input.nextLine();
            System.out.println("How costly is it?\n" + ratings);
            cost = Integer.parseInt(input.nextLine());
            System.out.println("How tastey is it?\n" + ratings);
            taste = Integer.parseInt(input.nextLine());
            System.out.println("How difficult is it to get?\n" + ratings);
            time = Integer.parseInt(input.nextLine());
            Meal tempMeal = new Meal(cost,taste,time,name);
            tempMeal.addToAllMeals();
            Meal.setMealCount(1);
            tempMeal.sortMeal();
            System.out.println(tempMeal.getName() + " recorded and sorted\n" +endLine);
            if(Meal.getMealCount() > 3)
            {
                enoughMeals = true;
                System.out.println(headingLine + "\nNEXT ACTION\n" + headingLine);
                System.out.println(endLine + "\nEnter 0 to log another meal, or any other number to get reports\n" + endLine);
                getReports = Integer.parseInt(input.nextLine());
            } 
        }
    }

    public static void getReports(int exit)
    {
        while(exit == 0)
        {
            System.out.println(headingLine + "\nREPORTS\n"+ headingLine);
            System.out.println(endLine + "\nPlease choose a menu option\n");
            System.out.println("[1] Sorted by Taste\n[2] Sorted by Cost\n[3] Sorted by Difficulty\n[4] Quality meals rank\n[5] Treat meals rank\n[6] Quick meals rank\n");
            exit = Integer.parseInt(input.nextLine());
            String report = Meal.getReport(exit);
            System.out.println(report);
            System.out.println("Enter 0 to get another report, or any other number to exit\n" + endLine);
            exit = Integer.parseInt(input.nextLine());
        }
    }

    public static void main(String[] args) {
        //Declarations
        Scanner inputMain = new Scanner(System.in);
        int finishLog;


        //Entry


        System.out.println(headingLine + "\nWELCOME TO THE MEAL RANKING APPLICATION\n"+ headingLine);
        System.out.println(endLine + "\nRank calculated using time taken, cost, and personal taste\nEnter 0 to continue\n" + endLine);
        finishLog = inputMain.nextInt();
        


        // Menus


        App.logMeal(finishLog);
        App.getReports(finishLog);
        


        // Exit Message


        System.out.println(headingLine + "\nGOODBYE\n"+ headingLine);
        System.out.println(endLine + "\nSee you next time\n" + endLine);

        inputMain.close();
        App.input.close();
 
    }
}
